### ISSUE TITLE
Date strings should have non-breaking spaces

### ISSUE THREAD

**Issue by Amselfass** [DeutscheModelUnitedNations/munify-delegator#91]
When full dates in the _4. November 2024_ format are shown to the user, the spaces should be replaced with `&nbsp;` to avoid ugly line breaks within the date.

For example: https://github.com/DeutscheModelUnitedNations/munify-delegator/blob/e42634457dbe78f28f134a55c32c595472752c53/src/lib/components/ConferenceCard.svelte#L104C8-L104C8

**Comment by TadeSF** [comment]
Phew, is that even possible with `toLocaleDateString()` @m1212e? I mean you could just use `replace()` but you also would not want text breaking anywhere because the it runs out of space and you don't want overflow either... Maybe just solve it with `ellipsis` and `no-wrap`? Also not that safe of an option.

Maybe just replacing the first space with a `&nbsp;` would be sufficient/a good solution? Or just not using long formats at all?

**Comment by m1212e** [comment]
Yes I think this would be more a CSS thing. Replacing Strings to adjust how the text is displayed isn't a good idea imo.

**Comment by Amselfass** [comment]
For the two reasons 

1. I think the no-break spaces can be considered part of the locale string itself
2. I don't know how to fix this in CSS 😄

I have made a PR to fix the issue using `replace()`. But I will not feel insulted if you reject it and fix the linebreak in another way. ;-)
